// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "kshmirko@dvo.ru"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate with email and password. Returns a JWT Bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request — validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/experiments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of experiments with optional filtering.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experiments"
                ],
                "summary": "List all experiments",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "description": "Sort direction",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "staged",
                            "uploading",
                            "done",
                            "failed"
                        ],
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by title (case-insensitive partial match)",
                        "name": "title",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ExperimentPaginatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Uploads licel zip, bgr and meteo files, creates an experiment and starts asynchronous preprocessing.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experiments"
                ],
                "summary": "Create experiment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Experiment title",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Experiment comments",
                        "name": "comments",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Licel measurements zip archive",
                        "name": "licelZip",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Licel BGR file",
                        "name": "licelBgr",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Meteo data file",
                        "name": "meteoFile",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ExperimentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/experiments/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single experiment by its database ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experiments"
                ],
                "summary": "Get experiment by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Experiment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ExperimentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/experiments/{id}/channels": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the list of available measurement channels (wavelength, polarization, photon/analog) for an experiment.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experiments"
                ],
                "summary": "Get experiment channels",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Experiment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ExperimentChannelsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/experiments/{id}/glue": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Starts asynchronous channel gluing for specified wavelengths and altitude range.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experiments"
                ],
                "summary": "Glue experiment channels",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Experiment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Glue parameters: wavelengths, polarization, altitude range h1-h2",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.GlueExperimentBody"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Glue task submitted",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Invalid experiment status",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/experiments/{id}/prepare": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Starts background processing: background subtraction and cropping. Stores result in Minio.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experiments"
                ],
                "summary": "Prepare experiment data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Experiment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Preparation parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.PrepareExperimentBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.PreparedExperimentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Experiment not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Experiment not ready",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/experiments/{id}/process": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Starts an async processing run (stage0, stage1, ...) on the experiment.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experiments"
                ],
                "summary": "Run processing algorithm on experiment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Experiment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Processing parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ProcessExperimentBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ProcessingRunResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Experiment not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Experiment not ready",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/prepared/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Enqueues a chart generation task (heatmap or profile) and returns a task ID for polling. Poll /tasks/{taskID} for the result.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experiments"
                ],
                "summary": "Visualize prepared experiment data (async)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Prepared experiment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "number",
                        "format": "float64",
                        "description": "Wavelength",
                        "name": "wavelen",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Photon/analog mode: 0=analog (default), 1=photon; ignored when glued=1",
                        "name": "photon",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "o",
                        "description": "Polarization",
                        "name": "polarization",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "image",
                            "profile"
                        ],
                        "type": "string",
                        "description": "image or profile",
                        "name": "action",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            0,
                            1
                        ],
                        "type": "integer",
                        "default": 0,
                        "description": "Glued mode: 0=non-glued (default), 1=glued",
                        "name": "glued",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "png",
                            "svg",
                            "json"
                        ],
                        "type": "string",
                        "default": "png",
                        "description": "Output type: png, svg or json",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "raw",
                            "rangecorr",
                            "lograngecorr"
                        ],
                        "type": "string",
                        "default": "raw",
                        "description": "Signal formula: raw, rangecorr, lograngecorr",
                        "name": "formula",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Force regeneration, ignoring cache",
                        "name": "regenerate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.VisualizeChartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/processing/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the current status of a processing run.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experiments"
                ],
                "summary": "Get processing run status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Processing Run ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ProcessingRunResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{taskID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the current status of an async task (pending, processing, done, failed). When done, includes the presigned chart URL.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Poll async task status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID returned by /prepared/{id}",
                        "name": "taskID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.TaskStatusResponse"
                        }
                    },
                    "404": {
                        "description": "Task not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of users with optional filtering by role, name and email.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List all users",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "description": "Sort direction",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "admin",
                            "guest",
                            "manager"
                        ],
                        "type": "string",
                        "description": "Filter by role",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by name (case-insensitive partial match)",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by email (case-insensitive partial match)",
                        "name": "email",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.UserPaginatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request — invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new user account. Email must be unique. Password is bcrypt-hashed. **Requires admin role.**",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User creation payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.CreateUserBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request — validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden — admin role required",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict — email already exists",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single user by its database ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request — invalid ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates user fields. If password is omitted, the existing password is preserved. **Requires admin role.**",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update existing user",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.UpdateUserBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request — validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden — admin role required",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permanently removes a user (soft-delete via GORM deleted_at). **Requires admin role.** Self-deletion is forbidden.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content — user deleted"
                    },
                    "400": {
                        "description": "Bad request — invalid ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden — admin role required or self-deletion",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_physicist2018_lidar-platform-go_pkg_dto.CreateUserBody": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 6
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "guest",
                        "manager"
                    ]
                }
            }
        },
        "github_com_physicist2018_lidar-platform-go_pkg_dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_physicist2018_lidar-platform-go_pkg_dto.ExperimentChannelResponse": {
            "type": "object",
            "properties": {
                "isActive": {
                    "description": "0 = no signal, 1 = has signal",
                    "type": "integer"
                },
                "isPhoton": {
                    "description": "0 = analog, 1 = photon",
                    "type": "integer"
                },
                "polarization": {
                    "type": "string"
                },
                "wavelen": {
                    "type": "number"
                }
            }
        },
        "github_com_physicist2018_lidar-platform-go_pkg_dto.ExperimentChannelsResponse": {
            "type": "object",
            "properties": {
                "channels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ExperimentChannelResponse"
                    }
                }
            }
        },
        "github_com_physicist2018_lidar-platform-go_pkg_dto.ExperimentPaginatedResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.ExperimentResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total_items": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "github_com_physicist2018_lidar-platform-go_pkg_dto.ExperimentResponse": {
            "type": "object",
            "properties": {
                "comments": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "error_msg": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "licel_bgr_path": {
                    "type": "string"
                },
                "licel_zip_path": {
                    "type": "string"
                },
                "measurement_start_time": {
                    "type": "string"
                },
                "measurement_stop_time": {
                    "type": "string"
                },
                "meteo_file_path": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_physicist2018_lidar-platform-go_pkg_dto.GlueExperimentBody": {
            "type": "object",
            "required": [
                "h1",
                "h2",
                "wavelengths"
            ],
            "properties": {
                "h1": {
                    "type": "number"
                },
                "h2": {
                    "type": "number"
                },
                "polarization": {
                    "type": "string"
                },
                "wavelengths": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "number"
                    }
                }
            }
        },
        "github_com_physicist2018_lidar-platform-go_pkg_dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "github_com_physicist2018_lidar-platform-go_pkg_dto.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.UserResponse"
                }
            }
        },
        "github_com_physicist2018_lidar-platform-go_pkg_dto.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_physicist2018_lidar-platform-go_pkg_dto.PrepareExperimentBody": {
            "type": "object",
            "required": [
                "bgr_type",
                "crop_alt"
            ],
            "properties": {
                "bgr_alt": {
                    "type": "number",
                    "minimum": 0
                },
                "bgr_type": {
                    "type": "string",
                    "enum": [
                        "file",
                        "avgTail",
                        "medTail"
                    ]
                },
                "crop_alt": {
                    "type": "number",
                    "minimum": 0
                }
            }
        },
        "github_com_physicist2018_lidar-platform-go_pkg_dto.PreparedExperimentResponse": {
            "type": "object",
            "properties": {
                "bgr_alt": {
                    "type": "number"
                },
                "bgr_type": {
                    "type": "string"
                },
                "crop_alt": {
                    "type": "number"
                },
                "error_msg": {
                    "type": "string"
                },
                "experiment_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "path_to_data": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_physicist2018_lidar-platform-go_pkg_dto.ProcessExperimentBody": {
            "type": "object",
            "required": [
                "algorithm",
                "params"
            ],
            "properties": {
                "algorithm": {
                    "type": "string"
                },
                "params": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "github_com_physicist2018_lidar-platform-go_pkg_dto.ProcessingRunResponse": {
            "type": "object",
            "properties": {
                "algorithm": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "error_msg": {
                    "type": "string"
                },
                "experiment_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "params": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_physicist2018_lidar-platform-go_pkg_dto.TaskStatusResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "error message (when failed)",
                    "type": "string"
                },
                "status": {
                    "description": "pending, processing, done, failed",
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                },
                "url": {
                    "description": "presigned Minio URL (when done)",
                    "type": "string"
                }
            }
        },
        "github_com_physicist2018_lidar-platform-go_pkg_dto.UpdateUserBody": {
            "type": "object",
            "required": [
                "email",
                "name",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 6
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "guest",
                        "manager"
                    ]
                }
            }
        },
        "github_com_physicist2018_lidar-platform-go_pkg_dto.UserPaginatedResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_physicist2018_lidar-platform-go_pkg_dto.UserResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total_items": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "github_com_physicist2018_lidar-platform-go_pkg_dto.UserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "github_com_physicist2018_lidar-platform-go_pkg_dto.VisualizeChartResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "\"accepted\" — task was enqueued",
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT Bearer token. Example: \"Bearer eyJhbGciOiJIUzI1NiIs...\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Lidar Platform API",
	Description:      "REST API for the Lidar Platform — user management, experiment processing.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
